name: Django CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Replace '3.x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r watchmate/requirements.txt  # Adjust the path if necessary

      - name: Run migrations
        run: python watchmate/manage.py migrate  # Adjust the path if necessary

      - name: Run tests
        run: python watchmate/manage.py test  # Adjust the path if necessary
